# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='message',
            new_name='qrcode_message',
        ),
    ]
