# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_auto_20171118_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='qrcode_message',
            new_name='message',
        ),
    ]
